# Generated by Django 4.1.4 on 2023-02-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='topic',
            fields=[
                ('topic_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
