# Generated by Django 4.1.4 on 2023-02-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_webpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='number',
            fields=[
                ('fstnum', models.IntegerField(primary_key=True, serialize=False)),
                ('lstnum', models.IntegerField()),
            ],
        ),
    ]
